### ISSUE TITLE
Requirement for a timelag column

### ISSUE THREAD

**Issue by bart1** [movestore/Add_Elevation#3]
This is more an enhancement than an issue as it is documented in the readme. But it seems a column `timelag` or `timelag2` is required. On first instance this quite counter intuitive to me as I just wanted elevations to be added to my dataset, for later work. An possible enhancement to the app would be to make it function without timelag.

**Comment by andreakoelzsch** [comment]
Thanks Bart! Indeed, if you do not select the option "adapt_alt", timelag or timelag2 are already now not required. I will change it in the documentation.

**Comment by bart1** [comment]
Ah I missed that interaction between options
